services:
  tomcat:
    image: tomcat
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./Corte1/clase03/target/clase03-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      # - ./cnf:/usr/local/tomcat/cofy10k
