version: "3.8"

services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  phpmyamd:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
volumes:
  my-db:
