package com.taller02.application.impl

import android.content.SharedPreferences
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import com.taller02.application.StoreService
import com.taller02.domain.Product

class SharedPreferencesStoreService(private val shp: SharedPreferences) : StoreService {
    // ! Generated by AI
    private val products = listOf(
        Product(1, "Smartphone X1", "", categories[0], 699.99, "Latest gen smartphone with OLED display", 50),
        Product(2, "Noise Cancelling Headphones", "", "Electronics", 299.49, "High-fidelity wireless over-ear headphones", 35),
        Product(3, "4K TV 55\"", "", categories[0], 799.00, "Ultra HD Smart TV with HDR support", 20),
        Product(4, "Gaming Mouse", "", categories[0], 59.99, "Ergonomic mouse with RGB lighting and 12 buttons", 100),
        Product(5, "Bluetooth Speaker", "", categories[0], 89.90, "Portable waterproof speaker with deep bass", 60),

        Product(6, "The Hobbit", "", categories[1], 19.99, "Fantasy novel by J.R.R. Tolkien", 120),
        Product(7, "Clean Code", "", categories[1], 45.00, "A Handbook of Agile Software Craftsmanship by Robert C. Martin", 30),
        Product(8, "1984", "", categories[1], 15.49, "Dystopian novel by George Orwell", 70),
        Product(9, "Atomic Habits", "", categories[1], 23.99, "Guide to building good habits by James Clear", 55),
        Product(10, "Dune", "", categories[1], 28.00, "Epic science fiction novel by Frank Herbert", 40),

        Product(11, "Men's Leather Jacket", "", categories[2], 120.00, "Stylish and warm black leather jacket", 25),
        Product(12, "Women's Summer Dress", "", categories[2], 49.99, "Floral pattern, lightweight, and breathable", 80),
        Product(13, "Running Shoes", "", categories[2], 89.99, "Comfortable and durable shoes for athletes", 60),
        Product(14, "Unisex Hoodie", "", categories[2], 39.50, "Casual hoodie with front pocket", 90),
        Product(15, "Jeans Slim Fit", "", categories[2], 59.95, "Dark wash stretch denim jeans", 70),

        Product(16, "Blender 700W", "", categories[3], 69.00, "Compact blender with multiple speed settings", 40),
        Product(17, "Non-stick Cookware Set", "", categories[3], 129.99, "10-piece kitchen set with non-stick coating", 30),
        Product(18, "Memory Foam Pillow", "", categories[3], 39.99, "Ergonomic pillow for neck and spine support", 100),
        Product(19, "LED Floor Lamp", "", categories[3], 54.00, "Adjustable lamp with remote control", 45),
        Product(20, "Vacuum Cleaner", "", categories[3], 149.90, "Bagless vacuum with HEPA filter", 25),

        Product(21, "LEGO Star Wars Set", "", categories[4], 89.99, "Buildable Starfighter set for ages 9+", 50),
        Product(22, "RC Car", "", categories[4], 59.95, "High-speed off-road remote-controlled car", 40),
        Product(23, "Barbie Dreamhouse", "", categories[4], 199.99, "Three-story playset with furniture and accessories", 15),
        Product(24, "Puzzle 1000 Pieces", "", categories[4], 18.49, "Scenic landscape puzzle", 75),
        Product(25, "Action Figures Pack", "", categories[4], 29.99, "Superhero figures, set of 5", 65),

        Product(26, "Smartwatch Series 5", "", categories[0], 249.00, "Fitness tracking, heart rate monitor, GPS", 40),
        Product(27, "To Kill a Mockingbird", "", categories[1], 14.99, "Classic novel by Harper Lee", 85),
        Product(28, "Yoga Pants", "", categories[2], 35.00, "Stretchy and comfortable for workouts", 100),
        Product(29, "Air Fryer", "", categories[3], 109.00, "Oil-less fryer for healthier meals", 30),
        Product(30, "Board Game - Catan", "", categories[4], 44.95, "Strategy game for 3-4 players", 50)
    )
    // End AI Generation
    companion object {
        const val CART_KEY = "cart"
        private val categories = listOf("Electronics", "Books", "Clothing", "Home", "Toys")
    }

    private val productMap = HashMap<Int, Product>()

    init {
        products.forEach { p ->
            productMap[p.id] = p
        }
        restoreCartAndAdjustStock()
    }

    override fun findAll(): List<Product> = products

    override fun findByCategory(category: String): List<Product> =
        products.filter { it.category == category }

    override fun getCategories(): List<String> = categories

    override fun findById(id: Int): Product =
        productMap[id] ?: throw NoSuchElementException("Product $id not found")

    // Cart, uses Gson to store it on
    override fun addToCart(id: Int, quantity: Int) {
        val product = findById(id)
        if (product.availableQuantity < quantity) throw IllegalStateException("Not enough stock")
        updateCart(id, quantity)
        productMap[id] = product.copy(availableQuantity = product.availableQuantity - quantity)
    }

    override fun getCart(): List<Product> {
        val cartMap = readCartMap()
        return cartMap.mapNotNull { (id, qty) ->
            productMap[id]?.copy(availableQuantity = qty)
        }
    }

    override fun removeFromCart(id: Int) {
        val cartMap = readCartMap()
        val removedQty = cartMap.remove(id) ?: return
        saveCartMap(cartMap)
        val product = productMap[id]
        if (product != null) {
            productMap[id] = product.copy(availableQuantity = product.availableQuantity + removedQty)
        }
    }


    private fun restoreCartAndAdjustStock() {
        val cart = readCartMap()
        cart.forEach { (id, qty) ->
            val product = productMap[id]
            if (product != null) {
                productMap[id] = product.copy(availableQuantity = (product.availableQuantity - qty).coerceAtLeast(0))
            }
        }
    }

    private fun readCartMap(): MutableMap<Int, Int> {
        val json = shp.getString(CART_KEY, null) ?: return mutableMapOf()
        val type = object : TypeToken<MutableMap<Int, Int>>() {}.type
        return Gson().fromJson(json, type)
    }

    private fun saveCartMap(cart: MutableMap<Int, Int>) {
        val json = Gson().toJson(cart)
        shp.edit().putString(CART_KEY, json).apply()
    }

    private fun updateCart(id: Int, quantity: Int) {
        val cart = readCartMap()
        cart[id] = (cart[id] ?: 0) + quantity
        saveCartMap(cart)
    }
}